general:
  debug: False ##vervoseも同じ
  exp_num: "002"
  device: 1
  seed: 42
  num_folds: 5 #10とかにしてもよい

loss:
  name: "bce" #"focal" "focal_cosine"

preprocess:
  size: 256
  select: True

aug:
  HorizontalFlip:
    p: 0.5
  VerticalFlip:
    p: 0.5
  RandomRotate90:
    p: 0.5
  ShiftScaleRotate:
    p: 0.7
    shift_limit: 0.1
    scale_limit: 0.1
    rotate_limit: 15
  RandomBrightnessContrast:
    p: 0
    brightness_limit: 0.1
    contrast_limit: 0.1
  CLAHE:
    p: 0
  one_of_Distortion:
    p: 0
  one_of_Blur_Gnoise:
    p: 0
  GridMask:
    p: 0
    num_grid: 2
  compress:
    p: 0
  CoarseDropout:
    p: 0.5
    max_holes: 4
    max_height: 6
    max_width: 6


augmentation:
  do_mixup: False
  do_fmix: False
  do_cutmix: False
  do_resizemix: False
  mix_p: 0
  mix_alpha: 1


model:
  name: "tf_efficientnet_b3_ns" #"tf_efficientnetv2_s" 
  # "coatnet_rmlp_1_rw_224","convnext_base_in22ft1k","swin_base_patch4_window7_224","tf_efficientnetv2_s" "maxvit_rmlp_nano_rw_256"
  #convnext　重い　efnetv2 s=b3とか？　#swin_large_patch4_window12_384 "tf_efficientnet_b0_ns"
  pooling: "gem" 
  n_classes: 1
  features_num: 1280 
  drop_rate: 0.1
  drop_path_rate: 0.1
  stride: 2 #


  
psuedo_label: 0 # "/home/u094724e/aimed2022/src/sub_rank_avg.csv" #or sub.csv


train:
  amp: True
  amp_inf: False 
  optim: "adamw" #"radam" "sam"#SAMはnoise robust
  lr: 0.001
  epochs: 10
  without_hesitate: 15
  batch_size: 6
  ga_accum: 1
  scheduler: 
    name: "cosine_warmup" #"cosine","cosine_warmup" #
    min_lr: 1e-7
    t_0: 3
    warmup: 3